//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SHOESSHOPEntities : DbContext
    {
        public SHOESSHOPEntities()
            : base("name=SHOESSHOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanList> BanLists { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Import> Imports { get; set; }
        public virtual DbSet<ImportUnit> ImportUnits { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductImg> ProductImgs { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeSho> TypeShoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<BanList1> BanList1 { get; set; }
        public virtual DbSet<Brand1> Brand1 { get; set; }
        public virtual DbSet<Cart1> Cart1 { get; set; }
        public virtual DbSet<Config1> Config1 { get; set; }
        public virtual DbSet<District1> District1 { get; set; }
        public virtual DbSet<Import1> Import1 { get; set; }
        public virtual DbSet<ImportUnit1> ImportUnit1 { get; set; }
        public virtual DbSet<Order1> Order1 { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Product1> Product1 { get; set; }
        public virtual DbSet<ProductImg1> ProductImg1 { get; set; }
        public virtual DbSet<Province1> Province1 { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
        public virtual DbSet<Ward1> Ward1 { get; set; }
        public virtual DbSet<Warehouse1> Warehouse1 { get; set; }
    }
}
