//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order1()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public string Code { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string AddressTo { get; set; }
        public string Phone { get; set; }
        public string AccountNumber { get; set; }
        public string AddressFrom { get; set; }
    
        public virtual User1 User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
