//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImg1
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Product1 Product { get; set; }
    }
}
