//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int Id { get; set; }
        public string UrlFile { get; set; }
        public string UrlLink { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> Status { get; set; }
        public int OrderNumber { get; set; }
    }
}
