<?xml version="1.0" encoding="utf-8"?><Database Name="TBPCCC" Class="DBTBPCCCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=125.212.192.18;Initial Catalog=TBPCCC;User ID=tuananh" SettingsObjectName="LibData.Properties.Settings" SettingsPropertyName="TBPCCCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CauHinh" Member="CauHinhs">
    <Type Name="CauHinh">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenCauHinh" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Giatri" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.HinhAnhSanPham" Member="HinhAnhSanPhams">
    <Type Name="HinhAnhSanPham">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenFile" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IdSanPham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SanPham_HinhAnhSanPham" Member="SanPham" ThisKey="IdSanPham" OtherKey="Id" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThuongHieu" Member="ThuongHieus">
    <Type Name="ThuongHieu">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenThuongHieu" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="XuatXuThuongHieu" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="SanXuatTai" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="ThuongHieu_SanPham" Member="SanPhams" ThisKey="Id" OtherKey="IdThuongHieu" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMucSanPham" Member="DanhMucSanPhams">
    <Type Name="DanhMucSanPham">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMuc" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="TenUrl" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(550)" CanBeNull="true" />
      <Column Name="IdDanhMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DanhMucSanPham_SanPham" Member="SanPhams" ThisKey="Id" OtherKey="IdDanhMuc" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.Slider" Member="Sliders">
    <Type Name="Slider">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenFile" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="TenUrl" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="IdDanhMuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdThuongHieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mota" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GiaSanPham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChatLieu" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="HuongDanBaoQuan" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HuongDanSudung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TenUrl" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenFileImage" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="SanPham_HinhAnhSanPham" Member="HinhAnhSanPhams" ThisKey="Id" OtherKey="IdSanPham" Type="HinhAnhSanPham" />
      <Association Name="DanhMucSanPham_SanPham" Member="DanhMucSanPham" ThisKey="IdDanhMuc" OtherKey="Id" Type="DanhMucSanPham" IsForeignKey="true" />
      <Association Name="ThuongHieu_SanPham" Member="ThuongHieu" ThisKey="IdThuongHieu" OtherKey="Id" Type="ThuongHieu" IsForeignKey="true" />
    </Type>
  </Table>
</Database>