//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportUnit
    {
        public ImportUnit()
        {
            this.Imports = new HashSet<Import>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> WardId { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<System.DateTime> IsUpdate { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<Import> Imports { get; set; }
        public virtual Province Province { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
