//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImg
    {
        public ProductImg()
        {
            this.Warehouses = new HashSet<Warehouse>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Color { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<Warehouse> Warehouses { get; set; }
    }
}
