//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int Id { get; set; }
        public string KeyCode { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> Discount { get; set; }
    }
}
