//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.Warehouses = new HashSet<Warehouse>();
        }
    
        public int Id { get; set; }
        public Nullable<double> US { get; set; }
        public Nullable<double> VN { get; set; }
        public Nullable<double> UK { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual ICollection<Warehouse> Warehouses { get; set; }
    }
}
